version: '3.9'
services:
  movie-service:
    image: movie_image
    container_name: movie-service
    build: MovieService/
    restart: always
    networks:
      - mynetwork
    ports:
      - 64100:64100
    depends_on:
      - mongoService
      - apigateway
      - eureka-service



  mongoService:
    image: mongo
    container_name: mongoService
    ports:
      - 27017:27017
    networks:
      - mynetwork

  authentication-service:
    image: authentication_image
    container_name: authentication-service
    build: UserAuthentication/
    restart: always
    networks:
      - mynetwork
    ports:
      - 64200:64200
    depends_on:
      - mysqlService
      - apigateway
      - eureka-service


  mysqlService:
    image: mysql:latest
    container_name: mysqlService
    networks:
      - mynetwork
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  apigateway:
    container_name: apigateway
    build: demoapigateway/
    networks:
      - mynetwork

    ports:
      - 9500:9500
    depends_on:
      - eureka-service

  eureka-service:
    container_name: eureka-service
    build: Eurekaserverdemo/
    restart: always
    networks:
      - mynetwork
    ports:
      - 8761:8761

networks:
  mynetwork:
    driver: bridge